[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "bauri-st7735"
dynamic = ["version"]
description = 'Simple and Minimal Micropython Driver for ST7735 Displays'
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []
authors = [
  { name = "Palash Bauri", email = "palashbauri1@gmail.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = []

[project.urls]
Documentation = "https://github.com/bauripalash/bauri-st7735#readme"
Issues = "https://github.com/bauripalash/bauri-st7735/issues"
Source = "https://github.com/bauripalash/bauri-st7735"
